//ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//AUTH
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//TICKET
export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKET = "GET_TICKET";
export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const CLEAR_TICKET = "CLEAR_TICKET";
export const TICKET_ERROR = "TICKET_ERROR";
export const GET_PROJECT_TICKETS = "GET_PROJECT_TICKETS";

//PROJECTS
export const GET_PROJECTS = "GET_PROJECTS";
export const CLEAR_PROJECTS = "CLEAR_PROJECTS";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const GET_PROJECT = "GET_PROJECT";
export const CLEAR_PROJECT = "CLEAR_PROJECT";
